import React from 'react'

import './PrivacyPolicy.css'

function PrivacyPolicy() {
  return (
    <div className='privacypolicy'>
      <div className='page_header'>
        <h1>Privacy Policy</h1>
      </div>
      <div className='privacy_content'>
        <h1 className='content_header'>
        1. Introduction
        </h1>
        <p className='content_paras'>Excel operates excelmec.org (hereinafter referred to as “Service”).
          Our Privacy Policy governs your visit to excelmec.org, and explains how we collect, safeguard and disclose information that results from your use of our Service.
          We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
          Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).</p>
        <h1 className='content_header'>
        2. Definitions
        </h1>
        <p className='content_paras'>SERVICE means the excelmec.org website operated by Excel.</p>
        <p className='content_paras'>PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
        <p className='content_paras'>USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
        <p className='content_paras'>COOKIES are small files stored on your device (computer or mobile device).</p>
        <p className='content_paras'>DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
        <p className='content_paras'>DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
        <p className='content_paras'>DATA SUBJECT is any living individual who is the subject of Personal Data.</p>
        <p className='content_paras'>THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
        <h1 className='content_header'>
        3. Information Collection and Use
        </h1>
        <p className='content_paras'>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
        <h1 className='content_header'>
        4. Types of Data Collected
        </h1>
        <p className='content_paras'>
          <h2 className='cont_highlights'>
          Personal Data
          </h2>
          <p className='content_paras'>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:</p>
          <ol>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, Country, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ol>
        </p>
        <p className='content_paras'>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>
        <p className='content_paras'>
          <h2 className='cont_highlights'>Usage Data</h2>
          <p className='content_paras'>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).</p>
          <p className='content_paras'>This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          <p className='content_paras'>When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.</p>
        </p>
        <h1 className='content_header'>
        5. Use of Data
        </h1>
        <p className='content_paras'>Excel uses the collected data for various purposes:
        <ol>

        <li> To provide and maintain our Service;</li>

        <li>To notify you about changes to our Service.</li>
        <li>To allow you to participate in interactive features of our Service when you choose to do so.</li>
        <li>To provide customer support.</li>
        <li>To gather analysis or valuable information so that we can improve our Service.</li>
        <li>To monitor the usage of our Service.</li>
        <li>To detect, prevent and address technical issues.</li>
        <li>To fulfil any other purpose for which you provide it.</li>
        <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection.</li>

        <li>To provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc..</li>

        <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.</li>

        <li>In any other way we may describe when you provide the information.</li>

        <li>For any other purpose with your consent.</li>

        </ol>
        </p>
        <h1 className='content_header'>
        6. Retention of Data
        </h1>
        <p className='content_paras'>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.<br/>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
        <h1 className='content_header'>
        7. Security of Data
        </h1>
        <p className='content_paras'>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
        <h1 className='content_header'>
        8. Service Providers
        </h1>
        <p className='content_paras'>We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.<br/>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
        <h1 className='content_header'>
        9. Analytics
        </h1>
        <p className='content_paras'>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
        <h1 className='content_header'>
        10. Changes to This Privacy Policy
        </h1>
        <p className='content_paras'>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br/>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.<br/>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        <h1 className='content_header'>
        11. Contact Us
        </h1>
        <p className='content_paras'>If you have any questions about this Privacy Policy, please contact us by email: .</p>
      
      </div>
    </div>
  )
}

export default PrivacyPolicy